language: node_js
os: linux
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
notifications:
  email: false
cache:
  directories:
    - node_modules
jobs:
  include:
    - node_js: "12.16.1"
      dist: trusty
      env:
        - CHROMIUM=true
        - FLAKINESS_DASHBOARD_NAME="Travis Chromium (node12 + linux)"
        - FLAKINESS_DASHBOARD_BUILD_URL="${TRAVIS_JOB_WEB_URL}"
      before_install:
        - "sysctl kernel.unprivileged_userns_clone=1"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./travis/chromium.sh
    - node_js: "10.18.1"
      dist: trusty
      env:
        - CHROMIUM=true
        - FLAKINESS_DASHBOARD_NAME="Travis Chromium (node10 + linux)"
        - FLAKINESS_DASHBOARD_BUILD_URL="${TRAVIS_JOB_WEB_URL}"
      before_install:
        - "sysctl kernel.unprivileged_userns_clone=1"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./travis/chromium.sh
    - node_js: "10.18.1"
      os: windows
      script: 'npx eslint .'
      env:
        - CHROMIUM=true
        - FLAKINESS_DASHBOARD_NAME="Travis Chromium (node10 + linux)"
        - FLAKINESS_DASHBOARD_BUILD_URL="${TRAVIS_JOB_WEB_URL}"
    - node_js: "10.18.1"
      dist: trusty
      before_install:
        - "sysctl kernel.unprivileged_userns_clone=1"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "pyenv shell 3.6; pip3 install --user mozdownload"
        - "rm -rf $FIREFOX_HOME; mozdownload -t daily -d $FIREFOX_HOME/latest.tar.bz --log-level DEBUG"
        - "cd $FIREFOX_HOME; tar -xvf latest.tar.bz; cd -; ls $FIREFOX_HOME/firefox/firefox;"
      script: 'BINARY=$FIREFOX_HOME/firefox/firefox npm run funit'
      env:
        - FIREFOX=true
        - FLAKINESS_DASHBOARD_NAME="Travis Firefox Nightly (node10 + linux)"
        - FLAKINESS_DASHBOARD_BUILD_URL="${TRAVIS_JOB_WEB_URL}"
        - FIREFOX_HOME=$TRAVIS_HOME/firefox-latest
